<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-B5ADGL1" failures="1" tests="4" name="Test" time="0.148" errors="0" timestamp="2022-02-22T15:49:27 CST">
  <testcase classname="project.HrDept" name="Test3" time="0.021"/>
  <testcase classname="project.LoanDept" name="Test2" time="0.026">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at project.LoanDept.Test2(LoanDept.java:19)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="project.HrDept" name="bTest4" time="0.005"/>
  <testcase classname="project.HrDept" name="bTest4" time="0.007"/>
  <testcase classname="project.HrDept" name="Test5" time="0.0">
    <ignored/>
  </testcase> <!-- Test5 -->
</testsuite> <!-- Test -->
